//
//  MainViewController.swift
//  MySampleApp
//
//
// Copyright 2016 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-ios-swift v0.1
//

import UIKit
import Firebase
import SafariServices

//class MainViewController: UIViewController, HypeAdStoreDelegate {
class MainViewController: UIViewController {

    @IBOutlet var countLabel: UILabel!
    @IBOutlet var progressBar: KYCircularProgress!
    @IBOutlet var kolodaView: KolodaView!
    @IBOutlet var mainSpinner: UIActivityIndicatorView!
    
    
    //Create subview for kolodaView, add Koloda view, and pass protocols
    override func viewDidLoad() {
        super.viewDidLoad()
        
        mainSpinner.startAnimating()
        
        progressBar.lineWidth = 10.0
        progressBar.guideLineWidth = 10.0
        progressBar.progressGuideColor = UIColor(red: 212/255, green: 212/255, blue: 212/255, alpha: 1)
        progressBar.showProgressGuide = true
        progressBar.colors = [UIColor(red: 255/255, green: 56/255, blue: 73/255, alpha: 1)]
        
        kolodaView.dataSource = self
        kolodaView.delegate = self
        

        
    }

    
    @IBAction func onSwipeRightClicked(sender: AnyObject){
        kolodaView.swipe(SwipeResultDirection.Right)
    }
    @IBAction func onSwipeLeftClicked(sender: AnyObject){
        kolodaView.swipe(SwipeResultDirection.Left)
    }
    

}

// KolodaView protocol that determines what cards to show
extension MainViewController: KolodaViewDataSource{
    func kolodaNumberOfCards(koloda: KolodaView) -> UInt{
//        return UInt(downloadContentsIndices.count)
        return 6
        
    }
    
    //Return a new view (card) to show from ImageStore
    func koloda(koloda: KolodaView, viewForCardAtIndex index: UInt) -> UIView {

        let newView = UIView()
        let colorArray = [UIColor.blueColor(), UIColor.redColor(), UIColor.greenColor()]
        let index = arc4random_uniform(3)
        newView.backgroundColor = colorArray[Int(index)]
        return newView
    }
        
}

// Own implemenation upon swiping so can clear image cache of given card


extension MainViewController: KolodaViewDelegate {
    func koloda(koloda: KolodaView, didSwipedCardAtIndex index: UInt, inDirection direction: SwipeResultDirection) {
        
    
    }
    
    func koloda(koloda: KolodaView, didSelectCardAtIndex index: UInt) {
    }
    
    func koloda(kolodaDidRunOutOfCards koloda: KolodaView) {

    }
}

protocol MainViewControllerDelegate{
    func onSwipeUp(ad: HypeAd)
}





